### ISSUE TITLE
PR check

### ISSUE THREAD

**Issue by mtrunkat** [apifytech/http-request#3]
* RequestError
    * Do we need to include original error?  I’d just inherit the message, stack, …
    * I’d trim response as it might be large (this may not be possible for non-text ?)
* We need to improve test coverage
* At multiple places you miss return before resolve/reject causing these functions so be called multiple times.

**Comment by jancurn** [comment]
Few more notes from my side:

- please `use_this_convention.js` for JS files, we are using it everywhere
- regarding the errors, @mtrunkat is right, also the error message needs to contain the root cause, otherwise people will never find it

**Comment by petrpatek** [comment]
Fixed
