### ISSUE TITLE
Property maxRedirects is not working

### ISSUE THREAD

**Issue by petrpatek** [apifytech/http-request#6]
Got has a hardcoded max redirects value to `10`. I did a PR to got to have this property configurable.

**Comment by jancurn** [comment]
I've never experienced a situation where I'd need to change this value. I'd happily skip this feature unless somebody really needs it.

**Comment by petrpatek** [comment]
Unfortunately, I am the one. Sometimes TripAdvisor API gives me more than 10 redirects.

**Comment by jancurn** [comment]
Fair enough :)

**Comment by osullivanalan** [comment]
+1 also need this property exposed

**Comment by petrpatek** [comment]
Hopefully, this feature should be available in the next got release. See https://github.com/sindresorhus/got/issues/838.

**Comment by tugkan** [comment]
Current `got` version does not support this feature. It needs to be updated to `10+`

**Comment by mnmkng** [comment]
FIxed with got 11
